### ISSUE TITLE
Integrate OPSIN for normalizing IUPAC entities

### ISSUE THREAD

**Issue by rockt** [rockt/ChemSpot#1]

**Comment by rockt** [comment]
Integration finished. Next, I need to find a way to map InChI to ChemIDplus and vice versa (perhaps using the existing ChemIDPlus dictionary).

**Comment by dan2097** [comment]
I hope you are finding OPSIN useful. Just to note unlike v0.9.0, v1.2.0 is available from Maven Central.
For resolving against databases, depending on the database in question, you may find the parseToStdInchi method more useful than parseToInchi. The difference is that the standard InChIs will not contain a layer indicating the specific tautomer a name described.

**Comment by rockt** [comment]
Thanks Daniel! I'll switch to v1.2.0 and use standard InChIs for normalization. The Jochem dictionary used by ChemSpot has InChIs for its terms as well... so I guess InChI is the best choice. Alternatively, one could also provide CAS Registry IDs.

**Comment by dan2097** [comment]
CAS numbers are problematic as they are not open. Resolvers that can resolve to/from CAS numbers are limited to compounds for which a CAS registry number was submitted as synonym. With InChIs it is simple for someone else to generate the same identifier are you.

**Comment by rockt** [comment]
Done
