### ISSUE TITLE
Maven import is missing eumed.jar dependency

### ISSUE THREAD

**Issue by tilschaef** [rockt/ChemSpot#27]

**Comment by rockt** [comment]
@thuber: could you fix that some time in the future? I don't have a project setup for ChemSpot anymore.

**Comment by thuber** [comment]
Yes, it will be fixed in the future. For now you can just delete the dependency in the pom.xml file, as the eumed.jar is not really needed yet.

**Comment by thuber** [comment]
Fixed. Dependency is now in eumed-light.jar.
